dataforgoodfr/batch_5_transplant

README.md, data/README.md, data/split_fct_tables.py
Cette PR modifie le README global et ajoute une section README pour la documentation de chacun des sets de données au sein du dossier data. 
Correction d'une erreur dans mon script également 
@armgilles @yannibenoit - Je vais merger direct ce sera plus simple. Lorsque le projet sera plus avancé et qu'il y aura plus de mondre, on fera plus gaffe.
=> [Documentation] Ajout de la documentation pour chaque dataset 

data/README.md
=> [Edit readme] modification readme

production/data_preparation/create_dataset.py
Je modifie la sélection des colonnes pour la création du `DimensionDataSet` en remplaçant la déclaration initiale des variables par datatype que @clembac avait faite. 
Trois dictionnaires permettent de sélectionner les variables pertinentes pour la constitution du set de dimension: 
- `pre_operatoire_cols `
- `donor_cols `
- `post_operatoire_cols `
Reviewer: @Max-Pol, @julamb, @yannibenoit, @clembac
=> [Production] Edit column selection in DimensionDataSet

transplant/tools/dataset.py
Cette PR refactor le code de la classe Dataset en prenant en compte la nouvelle façon de lire les données définie par @Max-Pol.
=> [Transplant Class] Refactor Dataset class

notebook/[TUTORIAL] How to load data.ipynb
Petit détail, mais pour éviter que d'autres soient bloqués, je modifie le path de clean qui était en doublon et qui faisait que je ne loadais pas dynamic_clean (cc @Max-Pol)
=> [Template Notebook] edit static vs dynamic clean path

transplant/tests/README.md, transplant/tests/tools/test_dataset.py, transplant/tools/dataset.py
J'ai ajouté une fonction `_sample_data` qui prend un data frame et qui en retourne une version restreinte selon les valeurs de `train` et `test`.
J'ai aussi écrit quelques tests pour vérifier que ça marche bien :)
=> add train/test split logic to dataset.py

scripts/build_clean_data_from_raw.py
Update du script `build_clean_data_from_raw.py`, afin d'ajouter la date_transplantation à la colonne "time" dans le csv des variables dynamiques.
=> [data][scripts] Add date_transplantation to column time in dynamic.csv

data/clean/static.csv, scripts/build_clean_data_from_raw.py
Cette PR modifie le script de cleaning des données pour la colonne `Survival_days_27_10_2018` qui contient une valeur égale à `xxx` (patient 405) et qui empêche de calculer ensuite la target variable. Je cast ensuite la variable `Survival_days_27_10_2018` en int.
J'ajoute également le csv clean qui supprime la ligne pour le patient 405. 
@Max-Pol
=> [Engineering] edit clean data raw script and add clean csv

data/norms/features_norm.json, transplant/config.py
J'ai crée un repo dans data pour mettre ce fichier mais c'est peut-être pas le bon endroit 
@martindaniel4 @julamb @Max-Pol
=> Ajout fichier json avec étendue et normes pour chaque variable dynamique

transplant/config.py, transplant/data/dataset.py
Cette PR fixe l'issue https://github.com/dataforgoodfr/batch_5_transplant/issues/42
Après discussion avec l'équipe Foch lors de [la réunion du 12 Décembre](https://docs.google.com/document/d/1XNNyPTxW1r_brAv4umtD2uMq_4AbhQcB619mGMQDSJQ/edit), un certain nombre de variables du set dynamiques doivent être supprimées. Cela soit parce qu'elles ajoutent du bruit, qu'elles ne sont pas utilisées par les équipes ou que les instruments de mesure ne sont pas branchés, fonctionnels.
=> [Data Quality] Supprimer les colonnes inutiles du set dynamique

notebooks/Data Quality - Share of NaN.ipynb
Rapide notebook pour mesurer la part des NaN au sein du set dynamique.
=> [Data Quality] add notebook share NaN

transplant/data/dataset.py
Cette PR supprime la restriction de la target sur test
=> [Class Dataset] remove restriction on test set target

notebooks/Modeling - Comparing Machine Learning Methods .ipynb, transplant/data/learningset.py
Dans /notebook: : Un notebook avec comparaison de modèles ML
Dans /transplant/data/ : Un script qu'utilise ce notebook pour les données statiques et dynamiques
=>  Notebook Comparaison ML Pierre + Script Learningset

transplant/visualization/graph.py
```python
from transplant.data.dataset import Dataset
from transplant.config import *
from transplant.visualization.graph import plot_dynamic_features
dataset = Dataset()
dataset.time_offset = 0  # To have full dynamic's data
train, test = dataset.get_dynamic()
df_dynamic = pd.concat([train, test])
plot_dynamic_features(df_dynamic, id_patient=302, 
features_list=['FC','FR', 'PAPmoy', 'SpO2', 'PASm'],
display_declampage=True)
```
=> [dataviz] afficher les event declampage durant l'opération

transplant/data/dataset.py
Fix #78 
```python
dataset = Dataset()
train, test = dataset.get_dynamic()
train.head(2)
```
```python
dataset = Dataset()
train, test = dataset.get_dynamic()
train.head(2)
```
=> Remove id_patient index

etudes/neural network/Pierre_UseKeras.ipynb, notebooks/Feature Selection _ t test.ipynb, notebooks/Modeling - Comparing Machine Learning Methods .ipynb, transplant/data/learningset.py
Notebook qui met à disposition de quoi faire des t test de signifiance de variables dans des modèles linéaires de type OLS.
Ce sont des tests standards en économétrie qui peuvent nous aider à choisir des variables.
-> Dans le fichier notebook : Feature Selection _ t test
J'ai dû aussi modifier un peu dans transplant.data.learningset la fonction get_data_merged_dynamic_flatten_full pour avoir accès à une table pandas.
=> Feature Selection - t test 

transplant/data/splitter.py, transplant/data/splitter_config.py, transplant/features/auc_features.py
1. Split dynamic's data into 3 DataFrame : 
- `baseline_data_df` : dynamic's data before first declampage. 
- `pre_declampage_df`:  dynamic's data between first and seconde declampage.
- `post_declampage_df`: dynamic's data after last declampage (aka 'money time`)
2. Calcul specifics features on this DataFrames : 
- Cacul Area Under the Curve (AUC) on specific features based on initial input done by operating room **OR** a median based on `baseline_data_df`
*Calcul AUC between a constant and a dynamic's features, AUC is the blue area*
To configure **splitters** (to split dynamic's data into 3 part) go to `transplant/data/splitter_config.py` : 
- `SPLITTER_PRE_FEATURES` : features to take for pre-declampage data.
- `SPLITTER_POST_FEATURES`: features to take for post-declampage data.
*Pre …
=> Armand split dynamic dataset

transplant/data/learningset.py
- Norme flake8
- Implémentation des splitters et AUC features dans `learningset`
```python
from transplant.data.learningset import Learningset
from transplant.config import *
learningset = Learningset()
train, test = learningset.get_data_merged_dynamic_flatten_full(fillna_auc=True, 
full_df=True)
train.shape
```
If you want to fillna (replace NaN value by 0) all AUC features, use `fillna_auc=True`. 
All AUC features are tunable in `transplant/data/splitter_config.py`
=> Armand learningset implementation

transplant/data/dataset.py, transplant/data/learningset.py, transplant/data/splitter_config.py, transplant/features/advanced_features.py
PR basé sur #91 
- Création de la variable `SpO2_by_FiO2` (SpO2 / FiO2) dans `dataset`
- Ajout d'un script dans `transplant/feature/advanced_features` : 
- Pouvoir appeler une function pour la création de nouvelles features dans `learningset`
- Création de `count_NaN` afin de compter le nombre d'indicateur `NaN` une fois les indicateurs dynamiques agrégés.
- La variable `SpO2_by_FiO2` est pris en compte dans le calcul des AUC. (cf `splitter_config.py`)
- Ajout d'un argument dans  `learningset.get_data_merged_dynamic_flatten_full`, `fillna_original`[bool] afin de choisir si on remplace les valeurs `NaN` par 0.
Si vous avez des nouvelles idées de variables techniques ou métiers (comme `SpO2_by_FiO2`), c'est le moment ;)
=> Armand add feature

transplant/tools/analyse_prediction.py
Fonctions afin de faciliter l'analyse des résultats de l'algo en vu de l'améliorer.
```python
from transplant.tools.analyse_prediction import *
result = analyse_prediction(model, # your model
X_test,  # classic test set (original)
y_test,   # your target
features_list=YOUR_FEATURE_SELECT # features to use for prediction
)
result.head()
```
```python
good, bad = get_good_bad_result(result)
good.head() # All your good prediction
bad.head() # All model's mistake
```
If you are curius to know why a patient if on `1`or `0`(win or fail)
```python
get_info_patient_operation(id_patient=3)
```
=> New script to improve analyse of our model
